name: Setup shellcheck
description: Download and install shellcheck
inputs:
  version:
    description: shellcheck version
    # renovate: datasource=github-releases depName=koalaman/shellcheck
    default: "aac0823e6b58f8a499e856e93738082691cbf212" # v0.11.0
runs:
  using: composite
  steps:
    - run: |
        REPO=koalaman/shellcheck
        TAG=$(git ls-remote --tags "https://github.com/${REPO}.git" \
          | grep "^${VERSION}" | head -1 \
          | sed -e 's|.*refs/tags/||' -e 's/\^{}//')
        if [ -z "$TAG" ]; then
          echo "::error::No tag found for SHA ${VERSION} in ${REPO}"
          exit 1
        fi
        BASE="https://github.com/${REPO}/releases/download/${TAG}"
        curl -sSL "${BASE}/shellcheck-${TAG}.linux.x86_64.tar.xz" \
          -o shellcheck.tar.xz
        tar -xJf shellcheck.tar.xz
        mv "shellcheck-${TAG}/shellcheck" /usr/local/bin/shellcheck
        rm -rf shellcheck.tar.xz "shellcheck-${TAG}"
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
