globs:
  - "**/*.md"

config:
  # Line length - disabled for prose-heavy files
  MD013: false
  # Blanks around headings - disabled for compact prompt files
  MD022: false
  # Allow duplicate headings (skills reuse headings across examples)
  MD024: false
  # Allow trailing punctuation in headings
  MD026: false
  # Blanks around fenced code blocks - disabled for compact prompt files
  MD031: false
  # Blanks around lists - disabled for compact prompt files
  MD032: false
  # Allow inline HTML
  MD033: false
  # Fenced code language - not always applicable
  MD040: false
  # First line doesn't have to be h1 (included files)
  MD041: false
  # Blanks around tables - disabled for compact prompt files
  MD058: false
  # Table column style - disabled for compact tables
  MD060: false

ignores:
  - ".pytest_cache/**"
  - "node_modules/**"
