ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - JSON_JSONLINT
  - JSON_PRETTIER
  - JSON_V8R
  - LUA_SELENE
  - LUA_STYLUA
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_RUFF
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_GITLEAKS
  - REPOSITORY_TRUFFLEHOG
  - SPELL_LYCHEE
  - YAML_PRETTIER
  - YAML_V8R
  - YAML_YAMLLINT

APPLY_FIXES: all
LINTER_RULES_PATH: .github/linters
FLAVOR_SUGGESTIONS: false

LUA_STYLUA_CONFIG_FILE: .stylua.toml

EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: '(\.chezmoiroot|\.chezmoiversion|\.chezmoitemplates/|home/dot_claude/)'

REPOSITORY_GIT_DIFF_DISABLE_ERRORS: true

SPELL_LYCHEE_CONFIG_FILE: .lychee.toml

MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "(home/dot_claude/)"

FILTER_REGEX_EXCLUDE: '(\.git/|node_modules/|\.pytest_cache/|\.ruff_cache/|\.tmpl$|home/dot_config/nvim/lazy-lock\.json)'

SHOW_ELAPSED_TIME: true
PRINT_ALL_FILES: false
