name: Setup actionlint
description: Download and install actionlint
inputs:
  version:
    description: actionlint version
    # renovate: datasource=github-releases depName=rhysd/actionlint
    default: "393031adb9afb225ee52ae2ccd7a5af5525e03e8" # v1.7.11
runs:
  using: composite
  steps:
    - run: |
        REPO=rhysd/actionlint
        TAG=$(git ls-remote --tags "https://github.com/${REPO}.git" \
          | grep "^${VERSION}" | head -1 \
          | sed -e 's|.*refs/tags/||' -e 's/\^{}//')
        if [ -z "$TAG" ]; then
          echo "::error::No tag found for SHA ${VERSION} in ${REPO}"
          exit 1
        fi
        VER="${TAG#v}"
        BASE="https://github.com/${REPO}/releases/download/${TAG}"
        curl -sSL "${BASE}/actionlint_${VER}_linux_amd64.tar.gz" \
          -o actionlint.tar.gz
        tar -xzf actionlint.tar.gz actionlint
        mv actionlint /usr/local/bin/actionlint
        rm -f actionlint.tar.gz
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
