name: Setup stylua
description: Download and install stylua
inputs:
  version:
    description: stylua version
    # renovate: datasource=github-releases depName=JohnnyMorganz/StyLua extractVersion=^v(?<version>.*)$
    default: '2.3.1'
runs:
  using: composite
  steps:
    - run: |
        curl -sSL "https://github.com/JohnnyMorganz/StyLua/releases/download/v${VERSION}/stylua-linux-x86_64.zip" -o stylua.zip
        unzip -o stylua.zip stylua
        mv stylua /usr/local/bin/stylua
        rm -f stylua.zip
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
