name: Setup stylua
description: Download and install stylua
inputs:
  version:
    description: stylua version
    # renovate: datasource=github-releases depName=JohnnyMorganz/StyLua
    default: '9c323db146963b04b919c83276d43ca7817da5e2' # v2.3.1
runs:
  using: composite
  steps:
    - run: |
        TAG=$(git ls-remote --tags https://github.com/JohnnyMorganz/StyLua.git | grep "^${VERSION}" | head -1 | sed -e 's|.*refs/tags/||' -e 's/\^{}//')
        if [ -z "$TAG" ]; then
          echo "::error::No tag found for SHA ${VERSION} in JohnnyMorganz/StyLua"
          exit 1
        fi
        curl -sSL "https://github.com/JohnnyMorganz/StyLua/releases/download/${TAG}/stylua-linux-x86_64.zip" -o stylua.zip
        unzip -o stylua.zip stylua
        mv stylua /usr/local/bin/stylua
        chmod +x /usr/local/bin/stylua
        rm -f stylua.zip
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
