name: Setup selene
description: Download and install selene
inputs:
  version:
    description: selene version
    # renovate: datasource=github-releases depName=Kampfkarren/selene
    default: "33a77154d008506b3443be363d4d8c265e01b104" # 0.30.0
runs:
  using: composite
  steps:
    - run: |
        REPO=Kampfkarren/selene
        TAG=$(git ls-remote --tags "https://github.com/${REPO}.git" \
          | grep "^${VERSION}" | head -1 \
          | sed -e 's|.*refs/tags/||' -e 's/\^{}//')
        if [ -z "$TAG" ]; then
          echo "::error::No tag found for SHA ${VERSION} in ${REPO}"
          exit 1
        fi
        BASE="https://github.com/${REPO}/releases/download/${TAG}"
        curl -sSL "${BASE}/selene-light-${TAG}-linux.zip" -o selene.zip
        unzip -o selene.zip -d selene-bin
        mv selene-bin/selene /usr/local/bin/selene
        chmod +x /usr/local/bin/selene
        rm -rf selene.zip selene-bin
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
