name: Setup ruff
description: Download and install ruff
inputs:
  version:
    description: ruff version
    # renovate: datasource=github-releases depName=astral-sh/ruff
    default: 'fcd50a0496d725f773c6da149035f98bd90b6a30' # 0.11.6
runs:
  using: composite
  steps:
    - run: |
        REPO=astral-sh/ruff
        TAG=$(git ls-remote --tags "https://github.com/${REPO}.git" \
          | grep "^${VERSION}" | head -1 \
          | sed -e 's|.*refs/tags/||' -e 's/\^{}//')
        if [ -z "$TAG" ]; then
          echo "::error::No tag found for SHA ${VERSION} in ${REPO}"
          exit 1
        fi
        BASE="https://github.com/${REPO}/releases/download/${TAG}"
        curl -sSL "${BASE}/ruff-x86_64-unknown-linux-gnu.tar.gz" \
          -o ruff.tar.gz
        tar -xzf ruff.tar.gz
        mv ruff-x86_64-unknown-linux-gnu/ruff /usr/local/bin/ruff
        rm -rf ruff.tar.gz ruff-x86_64-unknown-linux-gnu
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
