name: Setup shfmt
description: Download and install shfmt
inputs:
  version:
    description: shfmt version
    # renovate: datasource=github-releases depName=mvdan/sh extractVersion=^v(?<version>.*)$
    default: '3.12.0'
runs:
  using: composite
  steps:
    - run: |
        curl -sSL "https://github.com/mvdan/sh/releases/download/v${VERSION}/shfmt_v${VERSION}_linux_amd64" -o /usr/local/bin/shfmt
        chmod +x /usr/local/bin/shfmt
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
