name: Setup shfmt
description: Download and install shfmt
inputs:
  version:
    description: shfmt version
    # renovate: datasource=github-releases depName=mvdan/sh
    default: "8202166b7d1e3473a7c65eeac53ddbdb55d5b808" # v3.12.0
runs:
  using: composite
  steps:
    - run: |
        REPO=mvdan/sh
        TAG=$(git ls-remote --tags "https://github.com/${REPO}.git" \
          | grep "^${VERSION}" | head -1 \
          | sed -e 's|.*refs/tags/||' -e 's/\^{}//')
        if [ -z "$TAG" ]; then
          echo "::error::No tag found for SHA ${VERSION} in ${REPO}"
          exit 1
        fi
        BASE="https://github.com/${REPO}/releases/download/${TAG}"
        curl -sSL "${BASE}/shfmt_${TAG}_linux_amd64" \
          -o /usr/local/bin/shfmt
        chmod +x /usr/local/bin/shfmt
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
